import * as ImageManipulator from "expo-image-manipulator";
import * as ImagePicker from "expo-image-picker";
import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import Constants from "expo-constants";
import { createVideoPlayer } from "expo-video";
import { Platform } from "react-native";
import { FairFaresCrypto } from "../../modules/fairfares-crypto/src";

// The thumbnail stays inside the per-device end-to-end encrypted descriptor;
// it is never stored as a public image. Start at a useful chat-bubble
// resolution and progressively reduce it only when a detailed frame would
// exceed the encrypted-envelope allowance. The 18 KB ceiling still leaves
// room for descriptor JSON, NaCl and base64 overhead.
const CHAT_THUMBNAIL_MAX_BYTES = 18_000;
const IS_EXPO_GO = Constants.appOwnership === "expo";
let mediaLibraryPickerActive = false;

async function launchPrivateMediaPicker(options: ImagePicker.ImagePickerOptions): Promise<ImagePicker.ImagePickerResult> {
  // A fast double tap can otherwise attempt to present two PHPicker/activity
  // controllers at once. Treat the duplicate tap like a cancellation instead
  // of leaking a native presentation error into the upload UI.
  if (mediaLibraryPickerActive) return { canceled: true, assets: null };
  mediaLibraryPickerActive = true;
  try {
    try {
      return await ImagePicker.launchImageLibraryAsync(options);
    } catch (error) {
      const reason = error instanceof Error ? error.message : String(error);
      // PHPicker normally needs no broad library permission. A few iOS
      // versions/devices can nevertheless route through the legacy picker
      // after permission state or an app upgrade changes. Recover once by
      // requesting access instead of surfacing a dead-end native error.
      if (Platform.OS === "android" && /unregistered ActivityResultLauncher/i.test(reason)) {
        // Some Android activity recreation paths can leave expo-image-picker's
        // launcher detached. The Storage Access Framework is independently
        // registered and gives the same user-controlled, per-file access.
        const fallback = await DocumentPicker.getDocumentAsync({
          type: "image/*",
          multiple: Boolean(options.allowsMultipleSelection),
          copyToCacheDirectory: true
        });
        if (fallback.canceled) return { canceled: true, assets: null };
        return {
          canceled: false,
          assets: fallback.assets.map((asset) => ({
            uri: asset.uri,
            width: 0,
            height: 0,
            type: "image" as const,
            fileName: asset.name,
            fileSize: asset.size,
            mimeType: asset.mimeType || "image/jpeg"
          }))
        };
      }
      if (Platform.OS !== "ios" || !/permission|photo(?: library)? access|rejected/i.test(reason)) throw error;
      const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(false);
      if (permission.granted || permission.accessPrivileges === "limited") {
        return await ImagePicker.launchImageLibraryAsync(options);
      }
      throw new Error("PHOTO_LIBRARY_SETTINGS_REQUIRED");
    }
  } finally {
    mediaLibraryPickerActive = false;
  }
}

function decodedBase64Size(value: string) {
  const padding = value.endsWith("==") ? 2 : value.endsWith("=") ? 1 : 0;
  return Math.max(0, Math.floor(value.length * 3 / 4) - padding);
}

export async function createLightweightChatThumbnail(uri: string) {
  let width = 480;
  let quality = 0.78;
  for (let attempt = 0; attempt < 7; attempt += 1) {
    const thumbnail = await ImageManipulator.manipulateAsync(uri, [{ resize: { width } }], {
      base64: true,
      compress: quality,
      format: ImageManipulator.SaveFormat.JPEG
    });
    try {
      const base64 = thumbnail.base64 || "";
      if (base64 && decodedBase64Size(base64) <= CHAT_THUMBNAIL_MAX_BYTES) return base64;
    } finally {
      if (Platform.OS !== "web" && thumbnail.uri && thumbnail.uri !== uri) {
        await FileSystem.deleteAsync(thumbnail.uri, { idempotent: true }).catch(() => undefined);
      }
    }
    width = Math.max(128, Math.round(width * 0.86));
    quality = Math.max(0.36, quality - 0.06);
  }
  // A thumbnail is an optimization, never a reason to block the attachment.
  return "";
}

export async function createLightweightVideoThumbnail(uri: string) {
  // Expo Go is a generic native host and does not provide a stable lifecycle
  // for expo-video SharedRef thumbnail extraction on every iOS runtime. Keep
  // video selection usable there; embedded thumbnails are generated by the
  // linked native module in FairFares development and production builds.
  if (Platform.OS === "web" || IS_EXPO_GO) return "";
  const nativeThumbnail = await FairFaresCrypto.generateVideoThumbnail(uri, CHAT_THUMBNAIL_MAX_BYTES).catch(() => "");
  if (nativeThumbnail) return nativeThumbnail;
  if (Platform.OS === "ios") {
    // Thumbnail extraction is optional. Never fall through to an expo-video
    // player on iOS: creating a SharedRef player while the picker-owned asset
    // is being handed across JSI can abort the process (rather than throw),
    // especially for larger files or codecs without an early decodable frame.
    // The composer and message bubble already provide a safe placeholder.
    return nativeThumbnail;
  }
  const player = createVideoPlayer(uri);
  let frames: Awaited<ReturnType<typeof player.generateThumbnailsAsync>> = [];
  try {
    // The native player decodes only a small frame near the start. Passing the
    // resulting SharedRef straight to ImageManipulator avoids a full video read
    // or a JS pixel-buffer copy.
    // Some encoders have no decodable sample at 100 ms. Try the first frame,
    // then two nearby timestamps instead of treating that codec detail as a
    // thumbnail failure.
    for (const time of [0, 0.1, 1]) {
      try {
        frames = await player.generateThumbnailsAsync(time, { maxWidth: 240, maxHeight: 240 });
        if (frames[0]) break;
      } catch {
        frames.forEach((candidate) => candidate.release());
        frames = [];
      }
    }
    const frame = frames[0];
    if (!frame) return "";
    let width = 480;
    let quality = 0.78;
    for (let attempt = 0; attempt < 7; attempt += 1) {
      const context = ImageManipulator.ImageManipulator.manipulate(frame);
      let rendered: Awaited<ReturnType<typeof context.renderAsync>> | undefined;
      let savedUri = "";
      try {
        rendered = await context.resize({ width }).renderAsync();
        const saved = await rendered.saveAsync({
          base64: true,
          compress: quality,
          format: ImageManipulator.SaveFormat.JPEG
        });
        savedUri = saved.uri;
        const base64 = saved.base64 || "";
        if (base64 && decodedBase64Size(base64) <= CHAT_THUMBNAIL_MAX_BYTES) return base64;
      } finally {
        rendered?.release();
        context.release();
        if (savedUri) await FileSystem.deleteAsync(savedUri, { idempotent: true }).catch(() => undefined);
      }
      width = Math.max(128, Math.round(width * 0.86));
      quality = Math.max(0.36, quality - 0.06);
    }
    return "";
  } finally {
    frames.forEach((frame) => frame.release());
    player.release();
  }
}

function preferredImageEncoding() {
  const webp = Platform.OS !== "ios";
  return {
    format: webp ? ImageManipulator.SaveFormat.WEBP : ImageManipulator.SaveFormat.JPEG,
    extension: webp ? "webp" : "jpg",
    mimeType: webp ? "image/webp" : "image/jpeg"
  };
}

async function compressedUpload(asset: ImagePicker.ImagePickerAsset, index: number, prefix: string, maxWidth: number, quality: number, maxBytes = 0) {
  const encoding = preferredImageEncoding();
  let currentWidth = maxWidth;
  let currentQuality = quality;
  let best = {
    uri: asset.uri,
    blob: undefined as Blob | undefined,
    size: Number(asset.fileSize || 0)
  };
  for (let attempt = 0; attempt < 5; attempt += 1) {
    const actions = asset.width && asset.width > currentWidth ? [{ resize: { width: currentWidth } }] : [];
    const compressed = await ImageManipulator.manipulateAsync(asset.uri, actions, {
      base64: false,
      compress: currentQuality,
      format: encoding.format
    });
    const blob = Platform.OS === "web" ? await fetch(compressed.uri).then((response) => response.blob()) : undefined;
    const info = Platform.OS === "web" ? null : await FileSystem.getInfoAsync(compressed.uri);
    const previousGeneratedUri = best.uri !== asset.uri ? best.uri : "";
    best = {
      uri: compressed.uri,
      blob,
      size: blob?.size || (info?.exists && "size" in info ? Number(info.size || 0) : 0)
    };
    if (Platform.OS !== "web" && previousGeneratedUri && previousGeneratedUri !== best.uri) {
      await FileSystem.deleteAsync(previousGeneratedUri, { idempotent: true }).catch(() => undefined);
    }
    if (!maxBytes || best.size <= maxBytes || currentWidth <= 720) break;
    currentWidth = Math.max(720, Math.round(currentWidth * 0.82));
    currentQuality = Math.max(0.42, currentQuality - 0.1);
  }
  const thumbnailBase64 = await createLightweightChatThumbnail(best.uri).catch(() => "");
  return {
    uri: best.uri,
    blob: best.blob,
    name: `${prefix}-${Date.now()}-${index + 1}.${encoding.extension}`,
    mimeType: encoding.mimeType,
    size: best.size,
    imageWidth: Number(asset.width || 0),
    imageHeight: Number(asset.height || 0),
    thumbnailBase64,
    ownedCacheFile: Platform.OS !== "web",
    kind: "IMAGE" as const
  };
}

export async function pickCompressedImages(limit = 4, maxWidth = 1280, quality = 0.72) {
  const remaining = Math.max(1, Math.min(limit, 4));
  // The system photo picker grants access only to the items the user selects.
  // It does not require broad Photo Library permission on supported iOS and
  // Android versions. Requesting that permission first incorrectly locked out
  // people who had denied full-library access even though the private picker
  // remained available.
  const result = await launchPrivateMediaPicker({
    allowsMultipleSelection: remaining > 1,
    base64: false,
    mediaTypes: ["images"],
    quality,
    selectionLimit: remaining
  });
  if (result.canceled) {
    return [];
  }
  const images: string[] = [];
  for (const asset of result.assets.slice(0, remaining)) {
    const encoding = preferredImageEncoding();
    const actions =
      asset.width && asset.width > maxWidth
        ? [{ resize: { width: maxWidth } }]
        : [];
    const compressed = await ImageManipulator.manipulateAsync(asset.uri, actions, {
      base64: true,
      compress: quality,
      format: encoding.format
    });
    if (compressed.base64) {
      images.push(`data:${encoding.mimeType};base64,${compressed.base64}`);
    }
  }
  return images;
}

export async function pickChatImages(limit = 4, maxWidth = 1280, quality = 0.62, maxBytes = 350_000) {
  const selectionLimit = Math.max(1, Math.min(limit, 4));
  const result = await launchPrivateMediaPicker({
    allowsMultipleSelection: selectionLimit > 1,
    base64: false,
    mediaTypes: ["images"],
    quality,
    selectionLimit
  });
  if (result.canceled || !result.assets.length) return [];
  return await Promise.all(result.assets.slice(0, selectionLimit).map((asset, index) =>
    compressedUpload(asset, index, "chitthi", maxWidth, quality, maxBytes)
  ));
}

export async function pickChatMedia(limit = 4, maxWidth = 1280, quality = 0.62, maxBytes = 350_000, maxVideoBytes = 100_000_000) {
  const selectionLimit = Math.max(1, Math.min(limit, 4));
  const result = await launchPrivateMediaPicker({
    allowsMultipleSelection: selectionLimit > 1,
    base64: false,
    mediaTypes: ["images", "videos"],
    quality,
    selectionLimit,
    videoMaxDuration: 120,
    // Keep selection lightweight and preserve the user's Original choice.
    // Data Saver performs one explicit, observable native export later; forcing
    // an export here caused a hidden double transcode and iOS cancellations.
    videoExportPreset: ImagePicker.VideoExportPreset.Passthrough,
    videoQuality: ImagePicker.UIImagePickerControllerQualityType.High
  });
  if (result.canceled || !result.assets.length) return [];
  const selectedVideo = result.assets.find((asset) => asset.type === "video");
  if (selectedVideo) {
    const blob = Platform.OS === "web" ? await fetch(selectedVideo.uri).then((response) => response.blob()) : undefined;
    const info = Platform.OS === "web" ? null : await FileSystem.getInfoAsync(selectedVideo.uri);
    const size = blob?.size || (info?.exists && "size" in info ? Number(info.size || 0) : Number(selectedVideo.fileSize || 0));
    if (!size) throw new Error("Could not determine the selected video size.");
    const videoLimit = Math.max(1_000_000, Math.min(100_000_000, maxVideoBytes));
    if (size > videoLimit) {
      if (Platform.OS !== "web") await FileSystem.deleteAsync(selectedVideo.uri, { idempotent: true }).catch(() => undefined);
      throw new Error(`This video is larger than the ${Math.round(videoLimit / 1_000_000)} MB encrypted-transfer limit currently enabled for your account.`);
    }
    const mimeType = selectedVideo.mimeType || "video/mp4";
    return [{
      uri: selectedVideo.uri,
      blob,
      name: selectedVideo.fileName || `chitthi-video-${Date.now()}${mimeType === "video/quicktime" ? ".mov" : ".mp4"}`,
      mimeType,
      size,
      // Do not decode video on the picker-critical path. The composer can be
      // shown immediately; iOS generates this preview asynchronously, and the
      // final thumbnail is regenerated from the prepared SDR rendition.
      thumbnailBase64: "",
      pickerAssetId: selectedVideo.assetId || undefined,
      ownedCacheFile: Platform.OS !== "web",
      kind: "VIDEO" as const
    }];
  }
  return await Promise.all(result.assets.slice(0, selectionLimit).map((asset, index) =>
    compressedUpload(asset, index, "chitthi", maxWidth, quality, maxBytes)
  ));
}

export async function takeChatPhoto(maxWidth = 1280, quality = 0.64, maxBytes = 400_000) {
  const permission = await ImagePicker.requestCameraPermissionsAsync();
  if (!permission.granted) throw new Error("Allow camera access to take a photo.");
  const result = await ImagePicker.launchCameraAsync({
    mediaTypes: ["images"],
    allowsEditing: false,
    base64: false,
    quality
  });
  if (result.canceled || !result.assets.length) return null;
  const asset = result.assets[0];
  return compressedUpload(asset, 0, "chitthi-camera", maxWidth, quality, maxBytes);
}
