import { ImageSourcePropType } from "react-native";

export const appAssets = {
  logo: require("../assets/fairfares-logo-mobile.png") as ImageSourcePropType,
  explorer: require("../assets/fairfares-explorer-button.png") as ImageSourcePropType,
  navHome: require("../assets/nav-home.png") as ImageSourcePropType,
  navServices: require("../assets/nav-services.png") as ImageSourcePropType,
  navActivity: require("../assets/nav-activity.png") as ImageSourcePropType,
  bed: require("../assets/icons8-double-bed.png") as ImageSourcePropType,
  roommates: require("../assets/icons8-roommates.png") as ImageSourcePropType,
  ride: require("../assets/icons8-ride.gif") as ImageSourcePropType,
  carpoolProfile: require("../assets/carpool-profile.png") as ImageSourcePropType,
  message: require("../assets/icons8-message.gif") as ImageSourcePropType,
  fchat: require("../assets/fchat-nav.png") as ImageSourcePropType,
  fchatWordmark: require("../assets/fchat-wordmark-white.png") as ImageSourcePropType,
  chittiMascot: require("../assets/chitti/chitti-mascot-mobile.png") as ImageSourcePropType,
  chittiLettersGold: require("../assets/chitti/chitti-letters-gold-mobile.png") as ImageSourcePropType,
  profile: require("../assets/account-nav.png") as ImageSourcePropType,
  serviceModify: require("../assets/service-modify.png") as ImageSourcePropType,
  serviceCancel: require("../assets/service-cancel.png") as ImageSourcePropType,
  serviceInvoice: require("../assets/service-invoice.png") as ImageSourcePropType,
  serviceEye: require("../assets/service-eye.png") as ImageSourcePropType,
  serviceHome: require("../assets/service-home.png") as ImageSourcePropType,
  serviceSupport: require("../assets/service-support.png") as ImageSourcePropType,
  search: require("../assets/icons8-magnifying-glass.png") as ImageSourcePropType,
  arrowUp: require("../assets/icons8-up-94.png") as ImageSourcePropType,
  arrowDown: require("../assets/icons8-arrow-down-94.png") as ImageSourcePropType,
  carFallback: require("../assets/car-toyota-corolla.jpg") as ImageSourcePropType,
  housingRentalPromo: require("../assets/housing-rental-promo-mobile.jpg") as ImageSourcePropType,
  exportsImportsPromo: require("../assets/exports-imports-coming-soon-mobile.jpg") as ImageSourcePropType,
  rentalPromo: require("../assets/rental-car-promo-mobile.jpg") as ImageSourcePropType,
  carpoolPoster: require("../assets/carpool-share-cost.jpg") as ImageSourcePropType,
  rideShareStrip: require("../assets/ride-share-strip-mobile.png") as ImageSourcePropType,
  rideListCarpoolBanner: require("../assets/ride-list-carpool-banner-mobile.jpg") as ImageSourcePropType,
  festivals: {
    diwali: require("../assets/festivals/diwali-mobile.jpg") as ImageSourcePropType,
    holi: require("../assets/festivals/holi-mobile.jpg") as ImageSourcePropType,
    makarSankranti: require("../assets/festivals/makar-sankranti-mobile.jpg") as ImageSourcePropType,
    christmas: require("../assets/festivals/christmas-mobile.jpg") as ImageSourcePropType,
    republicDay: require("../assets/festivals/republic-day-mobile.jpg") as ImageSourcePropType,
    rakshaBandhan: require("../assets/festivals/raksha-bandhan-mobile.jpg") as ImageSourcePropType,
    navratri: require("../assets/festivals/navratri-mobile.jpg") as ImageSourcePropType,
    independenceDay: require("../assets/festivals/independence-day-mobile.jpg") as ImageSourcePropType
  }
};
